services:
  - type: web
    name: flipkart-backend
    env: node
    region: oregon
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: mongodb
          property: connectionString.standardSrv
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: NODE_OPTIONS
        value: --max_old_space_size=1024
    healthCheckPath: /api/health/ping
    autoDeploy: true
